
#General mod settings
[general]
	#Uses list of people to have omniscient targetting effect
	whiteListUsedOmniscient = false
	#Uses list of people to have senses spawned for
	whiteListUsedSenses = false
	#List of people to have omniscient targetting effect
	whitelistOmniscientTargettedPlayers = ""
	#List of people to have senses spawned for
	whitelistSenses = ""

